name: Update Major Tag

on:
  release:
    types: [released]
    
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

      - name: Check Tag
        if: ${{ !startsWith(github.ref_name, 'v') }}
        run: |
          echo "Tag must start with v in order to update the major"
          exit 1

      - uses: actions/checkout@v3

      - name: Update Tag
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
          export TAG_NAME="${GITHUB_REF##refs/tags/}"
          export TAG_MAJOR="${TAG_NAME%%.*}"
          git tag --force -a "${TAG_MAJOR}" -m "Release ${TAG_NAME}"
          git push --force origin "${TAG_MAJOR}"
